config:
  data_name: DiscreteSpectrumExample
  len_time: 51
  delta_t: 0.02
  num_real: 2
  num_complex_pairs: 0
  widths: [2, 30, 30, 2, 2, 30, 30, 2]
  hidden_widths_omega: [10, 10]
  shifts: [1,2,3,4,5,6,7,8,9,10]
  shifts_middle: [1,2,3,4,5,6,7,8,9,10]
  recon_lam: 0.1
  Linf_lam: 1.0e-7
  l2_lam: 1.0e-12
  batch_size: 256
  max_epochs: 2
  learning_rate: 0.001
  seed: 42
