data:
    name: RatAuditoryCortex
    root: data
    # root: /mnt/outputs/DeepKoopman_pytorch/data
    len_time: 251
    delta_t: 0.004
    train_files: 1
    shifts:
        start: 1
        stop: 101
        interval: 5
    middle_shifts:
        start: 1
        stop: 101
        interval: 5
model:
    widths:
        - 64
        - 256
        - 128
        - 3
        - 3
        - 128
        - 256
        - 64
    omega_hidden_widths:
        - 64
        - 64
    num_real: 1
    num_complex_pairs: 1
    activation: relu
loss:
    reconstruction_weight: 0.1
    middle_shift_weight: 1.0
    linf_weight: 1.0e-08
    l1_weight: 0.0
    l2_weight: 1.0e-13
optimizer:
    lr: 0.001
trainer:
    batch_size: 256
    max_epochs: 100
    # autoencoder_warmup_epochs: 5
callbacks:
    model_checkpoint:
        monitor: val/loss
        mode: min
        save_top_k: 1
        filename: best-{epoch:03d}
runtime:
    seed: 42
    dtype: float32
    device: auto
logging:
    backend: csv
